POST https://node-crud-1j57.onrender.com/videos
Content-Type: application/json

{
    "title": "Video Node pt3 final",
    "description": "Esse é o video 03 e o ultimo",
    "duration": 180
}

###

GET https://node-crud-1j57.onrender.com/videos

###

PUT https://node-crud-1j57.onrender.com/videos/cc56dfdf-5a4d-4589-8cc8-fc55e4150755
Content-Type: application/json

{
    "title": "video aleatoro",
    "description": "Esse é aleatorio",
    "duration": 180
}

###

DELETE https://node-crud-1j57.onrender.com/videos
/cc56dfdf-5a4d-4589-8cc8-fc55e4150755
