POST https://node-crud-g3c0.onrender.com/videos
Content-Type: application/json

{
    "title": "video Node",
    "description": "Esse é o video 01",
    "duration": 180
}

###

GET https://node-crud-g3c0.onrender.com/videos

###

PUT https://node-crud-g3c0.onrender.com/videos/1ecc0c4d-830e-41c8-8e8b-d9cfd395beee
Content-Type: application/json

{
    "title": "video Node",
    "description": "Esse é o sobre Node",
    "duration": 180
}

###

DELETE https://node-crud-g3c0.onrender.com/videos/1ecc0c4d-830e-41c8-8e8b-d9cfd395beee
